// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtvcyatbxbgkrzhxgfdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dmN5YXRieGJna3J6aHhnZmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMzA2MzUsImV4cCI6MjA2MzcwNjYzNX0.HeKr2ONSW5Qx4ASmAwogqdtFlrLaYXvC2oWaVg2Bj2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);